kumuluzee:
  name: image-comments-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/CommentsDS
      connection-url: jdbc:postgresql://35.205.56.107:5432/images_db
      username: postgres
      password: adminadmin
      pool:
        max-size: 20